FROM node:20-alpine

WORKDIR /opt/mkjs-server-deps

COPY server/package.json ./
RUN npm install

WORKDIR /app

EXPOSE 55555

CMD ["sh", "-c", "if [ ! -e /app/server/node_modules ]; then ln -s /opt/mkjs-server-deps/node_modules /app/server/node_modules; fi; cd /app/server && npm run dev"]