sonar.projectKey=Dannyeclisson_GCES-projetoindividual
sonar.organization=dannyeclisson
sonar.host.url=https://sonarcloud.io

sonar.sources=server,game
sonar.tests=server/test,server/fuzz
sonar.exclusions=server/node_modules/**,game/images/**,server/test/**,server/fuzz/**
sonar.sourceEncoding=UTF-8
